### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by anarion80** [sca075/valetudo_vacuum_camera#100]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Every now and then, without any action from the user, there are WARNINGs reporting errors in the log:

```
2024-03-18 09:17:36.089 WARNING (dreame1_camera_0) [custom_components.valetudo_vacuum_camera.valetudo.hypfer.image_handler] dreame1 : Error in get_image_from_json: list index out of range
Traceback (most recent call last):
  File "/config/custom_components/valetudo_vacuum_camera/valetudo/hypfer/image_handler.py", line 384, in async_get_image_from_json
    self.robot_pos = await self.async_get_robot_in_room(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/valetudo_vacuum_camera/valetudo/hypfer/image_handler.py", line 741, in async_get_robot_in_room
    self.zooming = bool(self.active_zones[self.robot_in_room["id"] + 1])
                        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
```

Full debug log below.

### What version of an integration has described problem?

v1.5.9

### What vacuum model do you have problems with?

Dreame L10 Pro

### Please firmware installed on your Vacuum.

Valetudo 2023.05.0

### What type of platform you use?

VEMLinux (Virtual Machine) such as Proxmox, VMWare, etc.

### What version of Home Assistant do you use?

core-2024.3.1

### What type of installation are you running?

Home Assistant Supervised

### Logs or Errors shown in the HA snapshots (please enable the Debug Mode)

```shell
2024-03-18 09:17:33.956 INFO (MainThread) [custom_components.valetudo_vacuum_camera.valetudo.MQTT.connector] Received dreame1 image data from MQTT
2024-03-18 09:17:36.083 DEBUG (MainThread) [custom_components.valetudo_vacuum_camera.valetudo.MQTT.connector] dreame1: Processing Hypfer data from MQTT.
2024-03-18 09:17:36.084 INFO (MainThread) [custom_components.valetudo_vacuum_camera.valetudo.MQTT.connector] dreame1: Extraction of Hypfer JSON Complete.
2024-03-18 09:17:36.085 INFO (dreame1_camera_0) [custom_components.valetudo_vacuum_camera.valetudo.hypfer.image_handler] dreame1: Composing the image for the camera.
2024-03-18 09:17:36.085 INFO (dreame1_camera_0) [custom_components.valetudo_vacuum_camera.valetudo.hypfer.image_handler] dreame1: Supporting Rooms Cleaning!
2024-03-18 09:17:36.085 INFO (dreame1_camera_0) [custom_components.valetudo_vacuum_camera.valetudo.hypfer.image_handler] Vacuum JSon ID: c2f13bac-5cad-42ff-ad94-8987072ac2e2 at Frame 0.
2024-03-18 09:17:36.087 DEBUG (dreame1_camera_0) [custom_components.valetudo_vacuum_camera.valetudo.hypfer.image_handler] dreame1: Got zones: {}
2024-03-18 09:17:36.088 DEBUG (dreame1_camera_0) [custom_components.valetudo_vacuum_camera.valetudo.hypfer.image_handler] dreame1: Got virtual walls: []
2024-03-18 09:17:36.089 DEBUG (dreame1_camera_0) [custom_components.valetudo_vacuum_camera.valetudo.hypfer.image_handler] dreame1: Got the points in the json: {'robot_position': [{'__class': 'PointMapEntity', 'metaData': {'angle': 97}, 'points': [3300, 3250], 'type': 'robot_position'}], 'charger_location': [{'__class': 'PointMapEntity', 'metaData': {'angle': 278}, 'points': [3300, 3250], 'type': 'charger_location'}]}
2024-03-18 09:17:36.089 WARNING (dreame1_camera_0) [custom_components.valetudo_vacuum_camera.valetudo.hypfer.image_handler] dreame1 : Error in get_image_from_json: list index out of range
Traceback (most recent call last):
  File "/config/custom_components/valetudo_vacuum_camera/valetudo/hypfer/image_handler.py", line 384, in async_get_image_from_json
    self.robot_pos = await self.async_get_robot_in_room(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/valetudo_vacuum_camera/valetudo/hypfer/image_handler.py", line 741, in async_get_robot_in_room
    self.zooming = bool(self.active_zones[self.robot_in_room["id"] + 1])
                        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
2024-03-18 09:17:36.094 DEBUG (MainThread) [custom_components.valetudo_vacuum_camera.camera_processing] dreame1: Camera frame processed.
2024-03-18 09:17:36.094 DEBUG (MainThread) [custom_components.valetudo_vacuum_camera.camera] dreame1: Output Gray Image.
2024-03-18 09:17:36.094 INFO (MainThread) [custom_components.valetudo_vacuum_camera.camera] Searching for /config/.storage/dreame1.png.
2024-03-18 09:17:36.096 DEBUG (MainThread) [custom_components.valetudo_vacuum_camera.camera] dreame1: Returning Snapshot image.
2024-03-18 09:17:36.198 DEBUG (MainThread) [custom_components.valetudo_vacuum_camera.camera] dreame1: Image update complete
2024-03-18 09:17:36.198 DEBUG (MainThread) [custom_components.valetudo_vacuum_camera.camera] Adjusted dreame1: Frame interval: 0.117
2024-03-18 09:17:36.201 DEBUG (MainThread) [custom_components.valetudo_vacuum_camera.camera] dreame1 System CPU usage stat: 4.7%
2024-03-18 09:17:36.201 DEBUG (MainThread) [custom_components.valetudo_vacuum_camera.camera] dreame1 Camera Memory usage in GB: 1.07, 18.38% of Total.
```

**Comment by sca075** [comment]
@anarion80 thanks for the report will investigate it and come back to you soon.

**Comment by sca075** [comment]
@anarion80 I think I found the root cause, the correction will come with the new version v1.6.0. Thanks once again for your report.

**Comment by sca075** [comment]
@anarion80 released v1.6.0 with the discussed fix. Will keep it open till you confirm the issue is solved.

**Comment by gosoares** [comment]
@sca075 I'm having a very similar issue and i have the latest version installed.

> Update for camera.roborock fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 950, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1293, in async_device_update
    await self.async_update()
  File "/config/custom_components/valetudo_vacuum_camera/camera.py", line 425, in async_update
    pil_img = await self.hass.async_create_task(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/valetudo_vacuum_camera/camera_processing.py", line 191, in run_async_process_valetudo_data
    images = await gather(*tasks)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/valetudo_vacuum_camera/camera_processing.py", line 169, in process_valetudo_data
    result = loop.run_until_complete(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/config/custom_components/valetudo_vacuum_camera/camera_processing.py", line 48, in async_process_valetudo_data
    pil_img = await self._map_handler.async_get_image_from_json(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/valetudo_vacuum_camera/valetudo/hypfer/image_handler.py", line 268, in async_get_image_from_json
    room_id, img_np_array = await self.imd.async_draw_base_layer(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/valetudo_vacuum_camera/valetudo/hypfer/image_draw.py", line 68, in async_draw_base_layer
    and self.img_h.active_zones[room_id + 1] == 1
        ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
IndexError: list index out of range

**Comment by sca075** [comment]
@gosoares thanks for the report may I will check the code there and get back to you as soon how many rooms do you have? can you please provide me your json file (it is in the camera logs **copy logs to www** option will copy a zip file that you can download with your file explorer or samba). I would run on it a couple of test to reproduce the issue and it will be then possible to fix it quite fast..

**Comment by sca075** [comment]
@gosoares I did publish the 2026.6.0 today, I guess we do have time offset. Will wait for the vacuum json file so that I can try to reproduce the issue. What model of vacuum is it? If I can reproduce the error you reported I will open an issue based on this conversation. Thanks a lot and once again in advance for your cooperation..

**Comment by gosoares** [comment]
@sca075 I'm sorry, i thought i had the latest version because hacs showed no update, but i double checked and i was actually in version 2025.05.2 (guess that was a typo in the release name).
I have update now to version 2024.06.0 and now i'm having actually [this](https://github.com/sca075/valetudo_vacuum_camera/issues/152) issue.

My vacuum is a Roborock S5 Max.

I did not understand how to get the json/logs as you describe, where is that option?

But i was able to get the related logs from my home assistant instance logs, is that what you need?

> 2024-05-26 22:31:06.739 INFO (MainThread) [homeassistant.setup] Setting up valetudo_vacuum_camera
> 2024-05-26 22:31:06.739 INFO (MainThread) [homeassistant.setup] Setup of domain valetudo_vacuum_camera took 0.00 seconds
> 2024-05-26 22:31:32.248 INFO (MainThread) [homeassistant.components.camera] Setting up valetudo_vacuum_camera.camera
> 2024-05-26 22:31:32.248 INFO (MainThread) [custom_components.valetudo_vacuum_camera.camera] System Release: homeassistant, 6.6.29-haos
> 2024-05-26 22:31:32.248 INFO (MainThread) [custom_components.valetudo_vacuum_camera.camera] System Version: #1 SMP PREEMPT_DYNAMIC Wed May  8 10:10:17 UTC 2024
> 2024-05-26 22:31:32.248 INFO (MainThread) [custom_components.valetudo_vacuum_camera.camera] System Machine: x86_64
> 2024-05-26 22:31:32.248 INFO (MainThread) [custom_components.valetudo_vacuum_camera.camera] Python Version: 3.12.2
> 2024-05-26 22:31:32.255 INFO (MainThread) [custom_components.valetudo_vacuum_camera.camera] Memory Available: 11673.1 and In Use: 4138.4
> 2024-05-26 22:31:32.764 INFO (MainThread) [custom_components.valetudo_vacuum_camera.valetudo.MQTT.connector] Received roborock image data from MQTT
> 2024-05-26 22:31:32.764 INFO (MainThread) [custom_components.valetudo_vacuum_camera.valetudo.MQTT.connector] roborock: Received vacuum docked status.
> 2024-05-26 22:31:32.764 INFO (MainThread) [custom_components.valetudo_vacuum_camera.valetudo.MQTT.connector] valetudo/roborock: Received vacuum Error: No error
> 2024-05-26 22:31:32.764 INFO (MainThread) [custom_components.valetudo_vacuum_camera.valetudo.MQTT.connector] valetudo/roborock: Received vacuum connection status: ready.
> 2024-05-26 22:31:32.765 INFO (MainThread) [custom_components.valetudo_vacuum_camera.valetudo.MQTT.connector] roborock: Received vacuum battery level: 100%.
> 2024-05-26 22:31:35.268 INFO (MainThread) [custom_components.valetudo_vacuum_camera.valetudo.MQTT.connector] roborock: Extraction of Hypfer JSON Complete.
> 2024-05-26 22:31:35.270 INFO (roborock_camera_0) [custom_components.valetudo_vacuum_camera.valetudo.hypfer.image_draw] 
> 2024-05-26 22:31:35.504 INFO (roborock_camera_0) [custom_components.valetudo_vacuum_camera.valetudo.hypfer.image_draw] 
> 2024-05-26 22:31:35.510 INFO (roborock_camera_0) [custom_components.valetudo_vacuum_camera.valetudo.hypfer.image_handler] 
> 2024-05-26 22:31:35.635 INFO (roborock_camera_0) [custom_components.valetudo_vacuum_camera.valetudo.hypfer.image_draw] 
> 2024-05-26 22:31:35.638 INFO (roborock_camera_0) [custom_components.valetudo_vacuum_camera.utils.drawable] Drawing roborock Robot With Angle: -8.0
> 2024-05-26 22:31:36.765 INFO (roborock_camera_0) [custom_components.valetudo_vacuum_camera.valetudo.hypfer.image_handler] 
> 2024-05-26 22:31:36.765 INFO (roborock_camera_0) [custom_components.valetudo_vacuum_camera.camera_processing] 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 950, in async_update_ha_state
>     await self.async_device_update()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1293, in async_device_update
>     await self.async_update()
>   File "/config/custom_components/valetudo_vacuum_camera/camera.py", line 439, in async_update
>     self.Image = await self.hass.async_create_task(
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/valetudo_vacuum_camera/camera.py", line 541, in run_async_pil_to_bytes
>     images = await gather(*tasks)
>              ^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/valetudo_vacuum_camera/camera.py", line 519, in process_pil_to_bytes
>     result = loop.run_until_complete(self.async_pil_to_bytes(pil_img))
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/config/custom_components/valetudo_vacuum_camera/camera.py", line 496, in async_pil_to_bytes
>     pil_img = await self.processor.run_async_draw_image_text(
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/valetudo_vacuum_camera/camera_processing.py", line 262, in run_async_draw_image_text
>     images = await gather(*tasks)
>              ^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/valetudo_vacuum_camera/camera_processing.py", line 235, in process_status_text
>     result = loop.run_until_complete(
>              ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/config/custom_components/valetudo_vacuum_camera/camera_processing.py", line 217, in async_draw_image_text
>     text, size = self._status_text.get_status_text(pil_img)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/valetudo_vacuum_camera/utils/status_text.py", line 80, in get_status_text
>     vacuum_state = self.translate_vacuum_status()
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/valetudo_vacuum_camera/utils/status_text.py", line 63, in translate_vacuum_status
>     translations = self.get_vacuum_status_translation(language)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/valetudo_vacuum_camera/utils/status_text.py", line 53, in get_vacuum_status_translation
>     translations.get("selector", {}).get("vacuum_status", {}).get("options", {})
>     ^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'get'
> 2024-05-26 22:31:54.951 INFO (MainThread) [custom_components.valetudo_vacuum_camera.valetudo.MQTT.connector] Received roborock image data from MQTT
> 2024-05-26 22:31:56.273 INFO (MainThread) [custom_components.valetudo_vacuum_camera.valetudo.MQTT.connector] No image data from valetudo/roborock,vacuum in docked status.
> 2024-05-26 22:31:56.273 INFO (MainThread) [custom_components.valetudo_vacuum_camera.camera] roborock: Image not processed. Returning not updated image.


Thanks for the help!

**Comment by sca075** [comment]
@gosoares the 2024.06.0 select the Configuration of the Camera, yo will have the Options menu,
![Screenshot 2024-05-23 at 19 21 35](https://github.com/sca075/valetudo_vacuum_camera/assets/82227818/346e1052-c10e-47c0-ab9d-bc36b3b9f56a)
 there is an **advanced menu** in the botthom.
![Screenshot 2024-05-23 at 19 21 59](https://github.com/sca075/valetudo_vacuum_camera/assets/82227818/2aaea931-b92e-494d-929d-57747ec25967)
Select Copy Camera Logs to WWW.
![Screenshot 2024-05-23 at 19 22 27](https://github.com/sca075/valetudo_vacuum_camera/assets/82227818/7dee7b07-79b7-44dc-b1e4-9e996c62953e)
Then please Copy Logs to WWW.
If all goes will be a roborock.zip in the www folder of Home assistant. 

The vacuum.roborock is normally a Rand256 Valetudo firmware, if it is an Hypfer firmware a more "creative name" and you may have from your vacuum an API menu in your local network. http://192.XXX.XXX.XXX/swagger/#/Robot/get_api_v2_robot_state_map
![Screenshot 2024-05-27 at 06 14 43](https://github.com/sca075/valetudo_vacuum_camera/assets/82227818/646c05f1-ea7c-4f19-8cee-2c816452b6f3)
This would be much more easy to get the vacuum Json I requested earlier.
it looks strange because I do test it with the S5 too and Max should be okay.. from the logs well it looks there is a serious environment issue.. I will be travelling for the next two weeks so.. it can be we can work on it..  I'm right now trying to understand what version of Valetudo do you use?

You can try to disable the status text anyhow from the logs, looks somehow it did startup, I did trap log the issue with the index.

**Comment by sca075** [comment]
@gosoares Thank You really much!! this trouble shouting is helping me a lot to find the week points in the code :)
Okay I did correct a couple lines on the status_text.py.. hopefully late today I will be able to publish it..
As I wrote above the **work around for the moment would be to disable the status text** and see if the image is display correctly, if you don't mind. Thanks again for your great cooperation.

**Comment by sca075** [comment]
@gosoares I just checked the data you provided, found the rout cause of the status text failure, and also confirmed that first and last segments are not generating the error you faced at the beginning. So in general if you could try to clean the segments 16 and 24 you might see a colour variance in the image.
I will need to check a couple of other things then I can try to publish a path just for you to fully test the camera. 
If you would star this project would mean really a lot to me. Thanks once again for the great cooperation.

**Comment by gosoares** [comment]
> what version of Valetudo do you use?

I forgot to reply this, i am using version 2024.02.0.

> and also confirmed that first and last segments are not generating the error you faced at the beginning. So in general if you could try to clean the segments 16 and 24 you might see a colour variance in the image.

I think the first error got fixed when i updated the integration. I just cleaned segments 16 and 24 and saw no color variances or warning.

> If you would star this project would mean really a lot to me. Thanks once again for the great cooperation.

I thought i already had done that. I just did it, thanks, its really helpful!
