### ISSUE TITLE
Deprecated alias Home Assistant 2024.5

### ISSUE THREAD

**Issue by tjorim** [sca075/valetudo_vacuum_camera#124]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

```
Logger: homeassistant.helpers.typing
Source: helpers/deprecation.py:206
First occurred: 22:13:04 (3 occurrences)
Last logged: 22:15:47

HomeAssistantType was used from valetudo_vacuum_camera, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'valetudo_vacuum_camera' custom integration
```

### What version of an integration has described problem?

2024.04.4

### What vacuum model do you have problems with?

n/a

### Please firmware installed on your Vacuum.

n/a

### What type of platform you use?

Intel NUC (or generic x86_64)

### What version of Home Assistant do you use?

core-2024.5.0b0

### What type of installation are you running?

Home Assistant OS

**Comment by sca075** [comment]
Yes I checked the beta and I'm pretty sure I know where's the problem but I will check this more in detail

**Comment by sca075** [comment]
It is the zlib_ng implemented in the connector.py will work on it later today.

**Comment by tjorim** [comment]
That's a separate error I got last night:
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/valetudo_vacuum_camera/valetudo/MQTT/connector.py:14
integration: Valetudo Vacuum Camera (documentation, issues)
First occurred: April 24, 2024 at 23:04:40 (1 occurrences)
Last logged: April 24, 2024 at 23:04:40

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1952, in async_forward_entry_setup
    return await self._async_forward_entry_setup(entry, domain, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1975, in _async_forward_entry_setup
    await integration.async_get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1069, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1146, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1116, in async_get_platforms
    await self.hass.async_add_import_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1059, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1233, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1265, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 144, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/valetudo_vacuum_camera/camera.py", line 114, in <module>
    from .valetudo.MQTT.connector import ValetudoConnector
  File "/config/custom_components/valetudo_vacuum_camera/valetudo/MQTT/connector.py", line 14, in <module>
    from zlib_ng import gzip_ng as gzip
ModuleNotFoundError: No module named 'zlib_ng'
```

This issue I created was about the `HomeAssistantType` (used on line 33 in custom_components/valetudo_vacuum_camera/camera.py). More info on the developers blog: https://developers.home-assistant.io/blog/2024/04/08/deprecated-backports-and-typing-aliases

**Comment by sca075** [comment]
@tjorim yep thank you for the help here. 

I did read the RN but the link you provided is more helpful.

Will have a look at it after work;)

**Comment by tjorim** [comment]
Changes related to the `zlib_ng`: https://github.com/home-assistant/core/pull/115767, and afterwards https://github.com/home-assistant/core/pull/115777.

**Comment by tjorim** [comment]
I thought it would be as simple as changing those lines from
```
 from zlib_ng import gzip_ng as gzip
 from zlib_ng import zlib_ng as zlib
```
to
```
from isal import igzip as gzip
from isal import isal_zlib as zlib
```
but now getting this error:
```
Logger: homeassistant.util.logging
Source: util/logging.py:98
First occurred: 12:55:18 (2 occurrences)
Last logged: 12:55:44

Exception in async_message_received when handling msg on 'valetudo/Alfred/BatteryStateAttribute/level': '99' Traceback (most recent call last): File "/config/custom_components/valetudo_vacuum_camera/valetudo/MQTT/connector.py", line 322, in async_message_received await self.hypfer_handle_battery_level(msg) File "/config/custom_components/valetudo_vacuum_camera/valetudo/MQTT/connector.py", line 208, in hypfer_handle_battery_level self._mqtt_vac_battery_level = int(bytes.decode(self._payload, "utf-8")) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: descriptor 'decode' for 'bytes' objects doesn't apply to a 'str' object
Exception in async_message_received when handling msg on 'valetudo/Alfred/BatteryStateAttribute/level': '98' Traceback (most recent call last): File "/config/custom_components/valetudo_vacuum_camera/valetudo/MQTT/connector.py", line 322, in async_message_received await self.hypfer_handle_battery_level(msg) File "/config/custom_components/valetudo_vacuum_camera/valetudo/MQTT/connector.py", line 208, in hypfer_handle_battery_level self._mqtt_vac_battery_level = int(bytes.decode(self._payload, "utf-8")) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: descriptor 'decode' for 'bytes' objects doesn't apply to a 'str' object
```

**Comment by sca075** [comment]
@tjorim 
> This issue I created was about the `HomeAssistantType` (used on line 33 in custom_components/valetudo_vacuum_camera/camera.py). More info on the developers blog: https://developers.home-assistant.io/blog/2024/04/08/deprecated-backports-and-typing-aliases


I did remove the line 33 on my test environment and there's no problem the permanent modification will be done later today.. Thanks again;)

**Comment by tjorim** [comment]
It seems to he used here: https://github.com/sca075/valetudo_vacuum_camera/blob/main/custom_components%2Fvaletudo_vacuum_camera%2Fcamera.py#L146 for typing. I think the proper way is to change the import.
