### ISSUE TITLE
Warning issues on v1.4.1 during migration.

### ISSUE THREAD

**Issue by sca075** [sca075/valetudo_vacuum_camera#34]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Some issue occurred during the migration due to typo and improper settings.

### What version of an integration has described problem?

v.1.4.1

### What was the last working version of an integration?

v1.4.0

### What vacuum model do you have problems with?

Roborock.V1

### Please firmware installed on your Vacuum.

2023.08.0

### What version of Home Assistant do you use?

2023.09.3

### What type of installation are you running?

Home Assistant OS

### Logs or Errors shown in the HA snapshots (please enable the Debug Mode)

```shell
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/valetudo_vacuum_camera/__init__.py:115
Integration: Valetudo Vacuum Camera (documentation, issues)
First occurred: 7:16:13 PM (2 occurrences)
Last logged: 7:16:13 PM

Error migrating entry upstairs-dreame Camera for valetudo_vacuum_camera
Error migrating entry downstairs-roborock Camera for valetudo_vacuum_camera
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/config_entries.py", line 635, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/etc/homeassistant/custom_components/valetudo_vacuum_camera/__init__.py", line 115, in async_migrate_entry
    _LOGGER("config update for v1.4.1 in progress...")
TypeError: 'HassLogger' object is not callable
```

### Additional information

We do have already a fix for it, we will test it and release it later today.

**Comment by sca075** [comment]
it is fixed on v1.4.2
