### ISSUE TITLE
Update for camera fails: AttributeError: '_idat' object has no attribute 'fileno'

### ISSUE THREAD

**Issue by Volkor3-16** [sca075/valetudo_vacuum_camera#54]
### Checklist

- [X] I have updated the integration to the latest version available
- [X] I have checked if the problem is already reported

### The problem

Let me preface this with I'm just blindly following the install guide here.  

When I get to the point of adding the Xiaomi map, it says "Invalid calibration, please check your configuration" and doesn't show a map.  

From what I can tell, even if the calibration is wrong, it should show the map?

![2023-12-11-21:38:27](https://github.com/sca075/valetudo_vacuum_camera/assets/4054374/a4bb5177-0286-4653-be33-6bdfbffc1c25)

### What version of an integration has described problem?

v1.5.0

### What vacuum model do you have problems with?

RoborockS5

### Please firmware installed on your Vacuum.

2023.10.0 - 002034

### What version of Home Assistant do you use?

2023.10.5

### What type of installation are you running?

Home Assistant Container

### Camera's settings.

```yaml
I'm not exactly sure how to get this, I checked around but could only find Image options, which are all default.

Camera Attributes (removed the massive amounts of rooms)

access_token: [redacted]
friendly_name: Ricky Camera
vacuum_status: docked
vacuum_topic: valetudo/ricky
vacuum_json_id: null
json_data: null
vacuum_position: null
calibration_points: null
snapshot: true
snapshot_path: /local/snapshot_ricky.png
rooms: [redacted for space]
entity_picture: /api/camera_proxy/camera.ricky_camera?token=[redacted]
supported_features: 1
```

### Logs or Errors shown in the HA snapshots (please enable the Debug Mode)

```shell
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:732
First occurred: 8:48:19 PM (2 occurrences)
Last logged: 9:26:41 PM
Update for camera.ricky_camera fails

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/PIL/ImageFile.py", line 515, in _save
    fh = fp.fileno()
         ^^^^^^^^^
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 732, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 991, in async_device_update
    await self.async_update()
  File "/config/custom_components/valetudo_vacuum_camera/camera.py", line 534, in async_update
    await self.take_snapshot(parsed_json, pil_img)
  File "/config/custom_components/valetudo_vacuum_camera/camera.py", line 398, in take_snapshot
    image_data.save(self.snapshot_img)
  File "/usr/local/lib/python3.11/site-packages/PIL/Image.py", line 2413, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.11/site-packages/PIL/PngImagePlugin.py", line 1398, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "/usr/local/lib/python3.11/site-packages/PIL/ImageFile.py", line 519, in _save
    _encode_tile(im, fp, tile, bufsize, None, exc)
  File "/usr/local/lib/python3.11/site-packages/PIL/ImageFile.py", line 530, in _encode_tile
    encoder.setimage(im.im, b)
SystemError: tile cannot extend outside image
```

### Additional information

I'm using an external MQTT server, running on a separate device. This MQTT works for other integrations (frigate). It has a custom username and password.

When opening 
`https://[homeassistantbaseurlhere]/api/camera_proxy/camera.ricky_camera?token=[redacted]`
I get a 500: Internal Server Error.  
However I'm not smart enough to know if that's the correct url.

Now this could all be a skill issue and I'm not configurating the right stuff, but the error from the log says this might not be on me 🙃

**Comment by sca075** [comment]
It is in any case a kind of strange.. if you can get the rooms means that MQTT isn't the issue (as well you aren't the only one using an external MQTT ;) ) I guess the issue is due to the auto trim function as it search for the first non background colour the first time only, then set the values for the trims in the memory. Please let me know if none of the above helped to solve the issue. I will investigate more deeply if not of course, I guess the none attribute for the jsonID is because the camera stopped to work, due to the error in HA.

**Comment by sca075** [comment]
@Volkor3-16 Any possibility from your side to confirm if by removing the crop (setting it at 100%) fixed your reported issue? If yes I will make some changes because a I thought about this issue yesterday and there could be an easy solution for it.

**Comment by Volkor3-16** [comment]
> @Volkor3-16 Any possibility from your side to confirm if by removing the crop (setting it at 100%) fixed your reported issue? If yes I will make some changes because a I thought about this issue yesterday and there could be an easy solution for it.

aha! that worked!

The downside is the logs now show the following - doesn't impact anything (yet - I assume blocking the main loop isn't great for performance)

```
 Logger: homeassistant.util.async_
Source: util/async_.py:137
First occurred: 6:17:04 PM (2 occurrences)
Last logged: 6:17:32 PM
Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for valetudo_vacuum_camera doing blocking calls at custom_components/valetudo_vacuum_camera/camera.py, line 597: f"{proc_insp.PsutilWrapper().psutil.cpu_percent(interval=self.frame_interval)}")
```

**Comment by sca075** [comment]
@Volkor3-16 yes I'm aware about that #53 ;) I will update soon the camera to v1.5.0 so that also this and #53 will be closed. Thanks again for your report this help really much :)

**Comment by sca075** [comment]
Released v1.5.1 with the fixes discussed above.
